# Generated by Django 5.2.13 on 2026-04-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_agent_contact_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Property listing', 'verbose_name_plural': 'Property listings'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Property image', 'verbose_name_plural': 'Property images'},
        ),
    ]
