# Generated by Django 5.2.13 on 2026-04-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_options_alter_propertyimage_options'),
        ('properties', '0005_property_purpose'),
    ]

    operations = [
    ]
