# Generated by Django 6.0.4 on 2026-04-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_agent_fk_replace_inline_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, help_text='Listing category label (e.g. Developed plot, Corner).', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_number',
            field=models.CharField(blank=True, help_text='Plot number for the details grid (e.g. 123).', max_length=50),
        ),
    ]
