# Generated by Django 5.2.13 on 2026-04-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_seo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='block',
            field=models.CharField(max_length=100),
        ),
    ]
