# Generated by Django 6.0.4 on 2026-04-30 13:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_property_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full listing copy: use the toolbar for bold, headings, lists, and links. HTML is shown on the property page.', verbose_name='Description'),
        ),
    ]
