# Generated by Django 6.0.4 on 2026-04-30 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_property_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(db_index=True, max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Mark when staff has reviewed this inquiry.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_emails', to='properties.property', verbose_name='Property listing')),
            ],
            options={
                'verbose_name': 'Listing email inquiry',
                'verbose_name_plural': 'Listing email inquiries',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('property_listing', 'sender_email'), name='listingemail_unique_listing_sender_email')],
            },
        ),
    ]
