# Generated by Django 5.1.6 on 2026-04-16 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(help_text='Full article body (plain text or HTML — rendered as HTML on the site if it contains tags).')),
                ('author_name', models.CharField(max_length=120)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News post',
                'verbose_name_plural': 'News posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/%Y/%m/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.newspost')),
            ],
            options={
                'verbose_name': 'News image',
                'verbose_name_plural': 'News images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
