# Generated by Django 5.2.13 on 2026-04-16 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='post',
            field=models.ForeignKey(help_text='One post can have many images; order with Sort order (lower first).', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.newspost'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='0 = first in gallery; use 1, 2, 3… to sequence multiple images.'),
        ),
    ]
