# Generated by Django 5.1.6 on 2026-04-16 11:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsimage_post_alter_newsimage_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Full article: use the toolbar for bold, headings, lists, and links. This HTML is shown on the website.'),
        ),
    ]
