# Generated by Django 5.2.13 on 2026-04-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_description_richtext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Article image', 'verbose_name_plural': 'Article images'},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-published_at'], 'verbose_name': 'News article', 'verbose_name_plural': 'News articles'},
        ),
    ]
