# Generated by Django 6.0.4 on 2026-04-30 13:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsimage_options_alter_newspost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full article: use the toolbar for bold, headings, lists, and links. This HTML is shown on the website.', verbose_name='Description'),
        ),
    ]
