# Generated by Django 6.0.4 on 2026-04-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newspost_slug_serial_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Leave blank to use the date and time when the article is saved.'),
        ),
    ]
